language: cpp
dist: trusty

matrix:
  fast_finish: true
  include:
    - name: linux gcc
      os: linux
      compiler: gcc
      env: DO_COVERAGE=true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost-regex-dev
    - name: linux clang
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - libboost-regex-dev
    - name: osx gcc
      os: osx
      compiler: gcc
      osx_image: xcode8.3
      addons:
        homebrew:
          packages:
            - gcc@6
    - name: osx clang
      os: osx
      compiler: clang
      osx_image: xcode8.3

before_install:
  # Setting environement
  - |
    if [[ "$DO_COVERAGE" == "true" ]] ; then
        export CMAKE_ARGS="-DCMAKE_CXX_FLAGS=--coverage -DCMAKE_C_FLAGS=--coverage"
        pip install --user codecov
    fi
  # Install Linux stuff
  - |
    if test "$TRAVIS_OS_NAME" == "linux"; then
        if test "$TRAVIS_COMPILER" == "gcc"; then
            export CC=gcc-4.9
            export CXX=g++-4.9
        elif test "$TRAVIS_COMPILER" == "clang"; then
            export CC=clang
            export CXX=clang++
        fi
    fi
  # Install OS X stuff
  - |
    if test "$TRAVIS_OS_NAME" == "osx"; then
        if test "$TRAVIS_COMPILER" == "gcc"; then
            export CC=gcc-6
            export CXX=g++-6
        elif test "$TRAVIS_COMPILER" == "clang"; then
            export CC=clang
            export CXX=clang++
        fi
    fi

script:
  - cd $TRAVIS_BUILD_DIR
  - ./scripts/check-whitespaces.py
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=debug $CMAKE_ARGS ..
  - make
  - ctest -L cfiles --output-on-failure
  - |
    if [[ "$DO_COVERAGE" == "true" ]] ; then
        cd $TRAVIS_BUILD_DIR
        codecov --gcov-exec=gcov-4.9
    fi
